theme = "darshan_new"

[editor]
completion-trigger-len = 1
line-number = "relative"
bufferline = "always"
color-modes = true
mouse = false
shell = ["zsh", "-c"]

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"
# prefix-len	
# max-wrap	
# max-diagnostics	

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "│"
# separator = "┊"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "total-line-numbers", "file-encoding"]
center = ["diagnostics", "workspace-diagnostics"]
right = [
  "position",
  "position-percentage",
  "spacer",
  "separator",
  "spacer",
  "version-control",
]

# KEYMAPS

[keys.normal]
"C-a" = "@<A-a>" # mine is mapped to A-a
"ret" = "@]<space>j"
"C-ret" = "@[<space>k"
"X" = "extend_line_above"
"Z" = ":wa"
"home" = "increment"
C-g = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload-all",
]

[keys.select]
X = "extend_line_above"

# to tackle global bindings.
[keys.insert]
"C-left" = "@<esc>b;i"                 # C-f
"C-right" = "@<esc>el;i"               # C-b
"home" = "@<esc>ghi"                   # C-a
"end" = "@<esc>glli"                   # C-e
"C-k" = "@<esc>t<ret>di"               # C-k
"C-u" = "@<esc>T<ret>di"               # C-u
"C-backspace" = "delete_word_backward" # C-w
"C-del" = "delete_word_forward"        # A-q

[keys.normal.space]
"q" = ":q"
