#!/usr/bin/env bash

MAX_BRIGHTNESS=800  # Set your max brightness value here (800 as per your question)

# Get brightness
get_backlight() {
    LIGHT=$(brightnessctl g)  # Get the current brightness value
    LIGHT_PERCENTAGE=$(echo "scale=0; $LIGHT * 100 / $MAX_BRIGHTNESS" | bc)  # Calculate percentage

    echo "${LIGHT_PERCENTAGE}"
}

# Notify user with current brightness
notify_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Brightness: $(get_backlight)%"
}

# Increase brightness
inc_backlight() {
    brightnessctl s +5% && notify_user
}

# Decrease brightness
dec_backlight() {
    if [[ "$(brightnessctl g)" -gt "$(($(brightnessctl m) * 10 / 100))" ]]; then
        brightnessctl s 5%-
    else
        brightnessctl s 10
    fi

    notify_user
}

# Execute based on input arguments
if [[ "$1" == "--get" ]]; then
    get_backlight
elif [[ "$1" == "--inc" ]]; then
    inc_backlight
elif [[ "$1" == "--dec" ]]; then
    dec_backlight
else
    get_backlight
fi
