name: Build & Push
permissions:
  contents: read

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Push Config
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      fail-fast: true # Stop all matrix jobs if one fails
    steps:
      - name: Free Disk Space
        uses: endersonmenezes/free-disk-space@v2
        with:
          remove_android: false # cleans a lot but very slow
          remove_packages_one_command: false # cleans a lot but very slow
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          # azure-cli google-cloud-cli dotnet-sdk-*, very slow 
          remove_packages: " microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* "
          remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/share/glade*  /usr/local/share/chromium /usr/local/share/powershell" # /usr/local/lib/node_modules, again, very slow

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with: 
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            max-jobs = auto
            download-buffer-size = 500000000
            substituters = https://cache.nixos.org https://nixpkgs-wayland.cachix.org https://helix.cachix.org https://hyprland.cachix.org https://yazi.cachix.org https://nix-community.cachix.org https://nix-gaming.cachix.org https://chaotic-nyx.cachix.org https://darshancommits.cachix.org  
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= helix.cachix.org-1:ejp9KQpR1FBI2onstMQ34yogDm4OgU2ru6lIwPvuCVs= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= yazi.cachix.org-1:Dcdz63NZKfvUCbDGngQDAZq6kOroIrFoyO064uvLh8k= anyrun.cachix.org-1:pqBobmOjI7nKlsUMV25u9QHa9btJK65/C8vnO3p346s= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= nix-gaming.cachix.org-1:nbjlureqMbRAxR1gJ/f3hxemL9svXaZF/Ees8vCUUs4= chaotic-nyx.cachix.org-1:HfnXSw4pj95iI/n17rIDy40agHj12WfF+Gqk6SonIT8= darshancommits.cachix.org-1:aITLC4uLnoX/hHdms6Jfj60BkH9e21DxGPz/IB0YMvw= 

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: darshancommits
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Builder
        run: |
          cachix watch-exec rishabh5321 -- \
            nix build .#nixosConfigurations.greeed.config.system.build.toplevel \
            -L --print-build-logs 
