name: Build & Push

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Push Config
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # if set to "true" but frees about 6 GB
          tool-cache: true # if build fails try with true

      - name: Clean /opt
        run: sudo rm -rf /opt

      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: darshancommits
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Builder
        run: nix build -L .#nixosConfigurations.greeed.config.system.build.toplevel
