name: Build & Push
permissions:
  contents: read

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Push Config
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      fail-fast: true # Stop all matrix jobs if one fails
    steps:
      - name: Free Disk Space
        uses: endersonmenezes/free-disk-space@v2
        with:
          remove_android: false # cleans a lot but very slow
          remove_packages_one_command: false # cleans a lot but very slow
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          # To free up more space, might be worth adding these. These are very slow to remove tho.
          # microsoft-edge-stable azure-cli google-cloud-cli dotnet-sdk-* google-chrome-stable firefox postgresql* mysql* 
          remove_packages: "temurin-* *llvm* "
          # /usr/share/miniconda /usr/local/lib/node_modules, again, very slow
          remove_folders: "/usr/share/swift /usr/share/az* /usr/share/glade* /usr/local/share/chromium /usr/local/share/powershell" 

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix(ummm, akshually Lix)
        uses: samueldr/lix-gha-installer-action@latest
        with: 
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            max-jobs = auto
            download-buffer-size = 500000000
            substituters = https://cache.nixos.org https://nixpkgs-wayland.cachix.org https://nix-community.cachix.org https://nix-gaming.cachix.org https://darshancommits.cachix.org  https://chaotic-nyx.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA=  nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= nix-gaming.cachix.org-1:nbjlureqMbRAxR1gJ/f3hxemL9svXaZF/Ees8vCUUs4= darshancommits.cachix.org-1:aITLC4uLnoX/hHdms6Jfj60BkH9e21DxGPz/IB0YMvw= chaotic-nyx.cachix.org-1:HfnXSw4pj95iI/n17rIDy40agHj12WfF+Gqk6SonIT8=

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: darshancommits
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Builder
        run: |
          cachix watch-exec darshancommits -- \
            nix build .#nixosConfigurations.greeed.config.system.build.toplevel \
            -L --print-build-logs 
