name: Build & Push

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Push Config
    runs-on: ubuntu-latest
    steps:
      - name: Clean /opt
        run: sudo rm -rf /opt

      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v15
        with:
          name: darshanCommits
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Builder
        run: nix build -L .#nixosConfigurations.nixos.config.system.build.toplevel

      - name: Deploy
        run: cachix push darshanCommits ./result*
